server:
  port: 9092
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: keshani
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      format-sql: true
  h2:
    console.enabled: true
app:
  cityImagePath: static/cityImages/
  cityImageUrl: http://localhost:9092/cityImages/
logging:
  level:
    com:
      citybuilder:
        cityviewer: DEBUG
  file: cityviewer.log
  path: /