server:
  port: 9092
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true