DROP TABLE IF EXISTS CITY_INFO;
DROP TABLE IF EXISTS CITY_DOCUMENT;

CREATE TABLE CITY_INFO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CITY_NAME VARCHAR(50) NOT NULL,
  CITY_DESCRIPTION VARCHAR(250) DEFAULT NULL,
  COUNTRY VARCHAR(50) DEFAULT NULL,
  LATITUDE DECIMAL(10,8),
  LONGITUDE DECIMAL(10,8)
);

CREATE TABLE CITY_DOCUMENT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  DOC_PATH VARCHAR(1000) NOT NULL,
  DOC_NAME VARCHAR(50) DEFAULT NULL,
  DOC_BELONGS_TO INT DEFAULT NULL,
  DOC_TYPE VARCHAR(20)
);

CREATE TABLE USERS (
  USER_ID VARCHAR(50) PRIMARY KEY ,
  USER_NAME VARCHAR(50),
  PASSWORD VARCHAR(50) NOT NULL,
  ENABLED TINYINT(4) DEFAULT NULL
);

CREATE TABLE ROLES(
  ROLE_ID INT AUTO_INCREMENT PRIMARY KEY ,
  ROLE_NAME VARCHAR(45) NOT NULL
);

CREATE TABLE USERS_ROLES (
  USER_ID VARCHAR(50) NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
INSERT INTO CITY_INFO( ID, CITY_NAME, CITY_DESCRIPTION, COUNTRY, LATITUDE, LONGITUDE)
  select convert("id",int), "name", "desciption", "country", convert("lat",decimal(10,8)), convert("lon",decimal(10,8))
  from CSVREAD( 'classpath:city.csv', 'id,name,desciption,country,lat,lon,photo', null );

  INSERT INTO CITY_DOCUMENT( ID, DOC_PATH, DOC_BELONGS_TO, DOC_TYPE)
    select convert("id",int), "path",convert("belongsto",int), "type"
    from CSVREAD( 'classpath:city_images.csv', 'id,path,belongsto,type', null );

  INSERT INTO USERS( USER_ID, PASSWORD, ENABLED)
  VALUES ('city_edit','city_password',1);

  INSERT INTO ROLES( ROLE_ID, ROLE_NAME)
  VALUES (1,'ROLE_ALLOW_EDIT');

  INSERT INTO USERS_ROLES(USER_ID, ROLE_ID)
  VALUES ('city_edit',1);

  INSERT INTO USERS( USER_ID, PASSWORD, ENABLED)
  VALUES ('city_fetch','city_password',1);
